guests = ['Dasha', 'Anton', 'Zhenya', 'Ira', 'Lena']
guests[1] = 'Polina'
# print(f'Приглашаю Вас, {guests[1]}, на обед.')
guests.insert(0, 'Sonya')
guests.insert(2, 'Liana')
guests.append('Nadya')
# print(f'Приглашаю Вас, {guests[0]}, на обед.')
# print(f'Приглашаю Вас, {guests[1]}, на обед.')
# print(f'Приглашаю Вас, {guests[2]}, на обед.')
# print(f'Приглашаю Вас, {guests[3]}, на обед.')
# print(f'Приглашаю Вас, {guests[4]}, на обед.')
# print(f'Приглашаю Вас, {guests[5]}, на обед.')
# print(f'Приглашаю Вас, {guests[6]}, на обед.')
# print(f'Приглашаю Вас, {guests[7]}, на обед.')
print('На обед приглашаются всего два гостя.')
popped_guests = guests.pop(0)
print(f'{popped_guests}, сожалеем об отмене приглашения.')
popped_guests = guests.pop()
print(f'{popped_guests}, сожалеем об отмене приглашения.')
popped_guests = guests.pop()
print(f'{popped_guests}, сожалеем об отмене приглашения.')
popped_guests = guests.pop()
print(f'{popped_guests}, сожалеем об отмене приглашения.')
popped_guests = guests.pop()
print(f'{popped_guests}, сожалеем об отмене приглашения.')
popped_guests = guests.pop()
print(f'{popped_guests}, сожалеем об отмене приглашения.')
print(f'{guests[0]}, приглашениее, высланное ранее, остаётся в силе.')
print(f'{guests[1]}, приглашениее, высланное ранее, остаётся в силе.')
del guests[0]
del guests[0]
print(f'{guests}')